language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
  - python: "3.7"
    dist: xenial
  - python: "pypy3.5"
    dist: xenial

install:
    - "python setup.py install"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install parameterized==0.7.0"

script:
    - "coverage run --source=pypika setup.py test"

after_success:
    coveralls
