language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
  - python: "3.7"
    dist: xenial

install:
    - "python setup.py install"
    - "pip install coverage"
    - "pip install coveralls"

script:
    - "coverage run --source=pypika setup.py test"

after_success:
    coveralls
